version: '2.1'
# networks: {}
volumes:
  resin-data: {}
services:
  main:
    build:
      context: .
      dockerfile: Raspberry/Dockerfile
    privileged: true
    restart: always
    network_mode: host
    volumes:
      - 'resin-data:/data'
      - /dev/video0:/dev/video0 
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'

