#!/bin/sh
#
# @name SDU Drone with Mono Camera
#
# @type Hexarotor x
#

. ${R}etc/init.d-posix/airframes/6014_sdu_drone

param set EKF2_AID_MASK 24
param set EKF2_HGT_MODE 2
param set EKF2_EV_DELAY 50